# -*- coding: utf-8 -*-
"""Credit Risk Training for AI Agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fo9q1JT-QfHd3WIslmAMaSAzal-FHqrO
"""


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
import joblib
import pandas as pd

credit = pd.read_csv("credit_risk.csv")

# -----------------------------
# Rename Columns
# -----------------------------

credit.rename(columns={
    "'checking_status'": "Checking_Status",
    "'duration'": "Duration",
    "'credit_history'": "Credit_History",
    "'purpose'": "Purpose",
    "'credit_amount'": "Credit_Amount",
    "'savings_status'": "Savings_Status",
    "'employment'": "Employment",
    "'installment_commitment'": "Installment_Commitment",
    "'personal_status'": "Relationship_Status",
    "'other_parties'": "Other_Parties",
    "'residence_since'": "Residence_Since",
    "'property_magnitude'": "Property_Type",
    "'age'": "Age",
    "'other_payment_plans'": "Other_Payment_Plans",
    "'housing'": "Living_Status",
    "'existing_credits'": "Existing_Credits",
    "'job'": "Job",
    "'num_dependents'": "Dependents",
    "'own_telephone'": "Telephone",
    "'foreign_worker'": "Foreign_Worker",
    "'class'": "Credit_Risk"
}, inplace=True)

# -----------------------------
# Remove ID
# -----------------------------

credit.drop("id", axis=1, inplace=True)

# -----------------------------
# Remove Duplicates
# -----------------------------

credit.drop_duplicates(inplace=True)

# -----------------------------
# Group Savings Categories
# -----------------------------

credit["Savings_Status"] = credit["Savings_Status"].replace({
    "<100": "Low Savings",
    "no known savings": "Low Savings",
    "100<=X<500": "Moderate Savings",
    "500<=X<1000": "High Savings",
    ">=1000": "High Savings"
})

# -----------------------------
# Group Property Categories
# -----------------------------

credit["Property_Type"] = credit["Property_Type"].replace({
    "car": "Small-Investment",
    "no known property": "No-Property",
    "real estate": "Significant Property",
    "life insurance": "Significant Property"
})

# -----------------------------
# Encode Target
# -----------------------------

credit["Credit_Risk"] = credit["Credit_Risk"].map({
    "good": 1,
    "bad": 0
})

# -----------------------------
# Feature Engineering
# -----------------------------

credit["Monthly_Burden"] = (
    credit["Credit_Amount"] /
    credit["Duration"]
)

credit["Multiple_Credits"] = (
    credit["Existing_Credits"] > 1
).astype(int)

# -----------------------------
# Age Bands
# -----------------------------

credit["Age_Group"] = pd.cut(
    credit["Age"],
    bins=[18, 30, 45, 60, 100],
    labels=[
        "Young",
        "Middle",
        "Senior",
        "Retired"
    ]
)

print(credit.head())
print(credit.shape)

# -----------------------------
# Features / Target
# -----------------------------

X = credit.drop("Credit_Risk", axis=1)
y = credit["Credit_Risk"]

# -----------------------------
# Categorical columns
# -----------------------------

categorical_cols = [
    "Checking_Status",
    "Credit_History",
    "Purpose",
    "Savings_Status",
    "Employment",
    "Relationship_Status",
    "Other_Parties",
    "Living_Status",
    "Job",
    "Telephone",
    "Foreign_Worker",
    "Property_Type",
    "Age_Group",
    "Other_Payment_Plans"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_cols
        )
    ],
    remainder="passthrough"
)

# -----------------------------
# XGBoost
# -----------------------------

model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# -----------------------------
# Complete Pipeline
# -----------------------------

pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", model)
    ]
)

# -----------------------------
# Train
# -----------------------------

pipeline.fit(X, y)

# -----------------------------
# Save entire pipeline
# -----------------------------

joblib.dump(
    pipeline,
    "credit_risk_pipeline.pkl"
)

print("Model trained and saved.")
